# Generated by Django 3.2.16 on 2023-01-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick', '0003_rename_subject_shop_shopname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shopname',
            field=models.CharField(max_length=50, verbose_name='店名'),
        ),
    ]
